services:

  marvin255_doctrine_translation_bundle.class_name_manager:
    class: Marvin255\DoctrineTranslationBundle\ClassNameManager\ClassNameManager

  Marvin255\DoctrineTranslationBundle\ClassNameManager\ClassNameManager:
    alias: marvin255_doctrine_translation_bundle.class_name_manager

  marvin255_doctrine_translation_bundle.locale_provider:
    class: Marvin255\DoctrineTranslationBundle\Locale\LocaleProvider
    arguments:
      - '@translation.locale_switcher'
      - '%kernel.default_locale%'

  marvin255_doctrine_translation_bundle.entity_manager_provider:
    class: Marvin255\DoctrineTranslationBundle\EntityManager\EntityManagerProvider
    arguments:
      - '@doctrine'

  marvin255_doctrine_translation_bundle.translation_repository:
    class: Marvin255\DoctrineTranslationBundle\Repository\TranslationRepository
    arguments:
      - '@marvin255_doctrine_translation_bundle.entity_manager_provider'
      - '@marvin255_doctrine_translation_bundle.locale_provider'
      - '@marvin255_doctrine_translation_bundle.class_name_manager'

  Marvin255\DoctrineTranslationBundle\Repository\TranslationRepository:
    alias: marvin255_doctrine_translation_bundle.translation_repository

  marvin255_doctrine_translation_bundle.translatable_state_handler:
    class: Marvin255\DoctrineTranslationBundle\StateHandler\TranslatableStateHandler
    arguments:
      - '@marvin255_doctrine_translation_bundle.entity_manager_provider'
      - '@marvin255_doctrine_translation_bundle.class_name_manager'

  Marvin255\DoctrineTranslationBundle\StateHandler\TranslatableStateHandler:
    alias: marvin255_doctrine_translation_bundle.translatable_state_handler

  marvin255_doctrine_translation_bundle.translatable_meta_event_subscriber:
    class: Marvin255\DoctrineTranslationBundle\EventSubscriber\TranslatableMetaDataEventSubscriber
    arguments:
      - '@marvin255_doctrine_translation_bundle.class_name_manager'
    tags:
      - 'doctrine.event_subscriber'

  marvin255_doctrine_translation_bundle.translation_meta_event_subscriber:
    class: Marvin255\DoctrineTranslationBundle\EventSubscriber\TranslationMetaDataEventSubscriber
    arguments:
      - '@marvin255_doctrine_translation_bundle.class_name_manager'
    tags:
      - 'doctrine.event_subscriber'

  marvin255_doctrine_translation_bundle.locale_normalizer:
    class: Marvin255\DoctrineTranslationBundle\Locale\LocaleNormalizer
    tags:
      - 'serializer.normalizer'
      - 'serializer.denormalizer'

  marvin255_doctrine_translation_bundle.translatable_type_extractor:
    class: Marvin255\DoctrineTranslationBundle\TypeExtractor\TranslatableTypeExtractor
    arguments:
      - '@marvin255_doctrine_translation_bundle.class_name_manager'
    tags: 
      - 'property_info.type_extractor'

  marvin255_doctrine_translation_bundle.translation_type_extractor:
    class: Marvin255\DoctrineTranslationBundle\TypeExtractor\TranslationTypeExtractor
    arguments:
      - '@marvin255_doctrine_translation_bundle.class_name_manager'
    tags: 
      - 'property_info.type_extractor'