services:

  Marvin255\DoctrineTranslationBundle\ClassNameManager\ClassNameManager:
    class: Marvin255\DoctrineTranslationBundle\ClassNameManager\ClassNameManager

  Marvin255\DoctrineTranslationBundle\EventSubscriber\TranslatableMetaDataEventSubscriber:
    class: Marvin255\DoctrineTranslationBundle\EventSubscriber\TranslatableMetaDataEventSubscriber
    arguments:
      - '@Marvin255\DoctrineTranslationBundle\ClassNameManager\ClassNameManager'
    tags: ['doctrine.event_subscriber']

  Marvin255\DoctrineTranslationBundle\EventSubscriber\TranslationMetaDataEventSubscriber:
    class: Marvin255\DoctrineTranslationBundle\EventSubscriber\TranslationMetaDataEventSubscriber
    arguments:
      - '@Marvin255\DoctrineTranslationBundle\ClassNameManager\ClassNameManager'
    tags: ['doctrine.event_subscriber']

  Marvin255\DoctrineTranslationBundle\Repository\EntityComparator:
    class: Marvin255\DoctrineTranslationBundle\Repository\EntityComparator
    arguments:
      - '@doctrine.orm.entity_manager'

  Marvin255\DoctrineTranslationBundle\Repository\TranslationRepository:
    class: Marvin255\DoctrineTranslationBundle\Repository\TranslationRepository
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@translation.locale_switcher'
      - '@Marvin255\DoctrineTranslationBundle\ClassNameManager\ClassNameManager'
      - '@Marvin255\DoctrineTranslationBundle\Repository\EntityComparator'
      - '%kernel.default_locale%'

  Marvin255\DoctrineTranslationBundle\Locale\LocaleNormalizer:
    class: Marvin255\DoctrineTranslationBundle\Locale\LocaleNormalizer
    tags: ['serializer.normalizer', 'serializer.denormalizer']

  Marvin255\DoctrineTranslationBundle\TypeExtractor\TranslatableTypeExtractor:
    class: Marvin255\DoctrineTranslationBundle\TypeExtractor\TranslatableTypeExtractor
    arguments:
      - '@Marvin255\DoctrineTranslationBundle\ClassNameManager\ClassNameManager'
    tags: ['property_info.type_extractor']

  Marvin255\DoctrineTranslationBundle\TypeExtractor\TranslationTypeExtractor:
    class: Marvin255\DoctrineTranslationBundle\TypeExtractor\TranslationTypeExtractor
    arguments:
      - '@Marvin255\DoctrineTranslationBundle\ClassNameManager\ClassNameManager'
    tags: ['property_info.type_extractor']