services:

  Marvin255\DoctrineTranslationBundle\EventSubscriber\TranslationMetaDataEventSubscriber:
    class: Marvin255\DoctrineTranslationBundle\EventSubscriber\TranslationMetaDataEventSubscriber
    tags: ['doctrine.event_subscriber']