name: Doctrine translation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  lint_and_test:
    name: Lint and test (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php-versions: ['8.1']
    steps:
    - uses: actions/checkout@v2
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
    - name: Get composer cache directory
      id: composer-cache-dir
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: Run linters
      run: composer run-script linter
    - name: Run test suite
      run: composer run-script test
    - name: Run infection
      run: composer run-script infection

  symfony_installation:
    name: Test installation to Symfony (PHP ${{ matrix.php-versions }}, Symfony ${{ matrix.symfony-versions }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.1']
        symfony-versions: ['6.1']
    env:
      SYMFONY_FOLDER: symfony_app
      DB_DATABASE: symfony
      DB_USERNAME: root
      DB_PASSWORD: password
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: symfony
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, dom, fileinfo, mysql, curl
      - name: Cache Symfony app
        id: symfony-app-cache
        uses: actions/cache@v2
        with:
          path: symfony_app_tmp
          key: ${{ runner.os }}-symfony-${{ matrix.symfony-versions }}-${{ matrix.php-versions }}
      - name: Install Symfony app
        if: steps.symfony-app-cache.outputs.cache-hit != 'true'
        run: |
          composer create-project symfony/skeleton:"${{ matrix.symfony-versions }}.*" symfony_app_tmp
          cd symfony_app_tmp
          composer require webapp
          echo "DATABASE_URL=mysql://${DB_USERNAME}:${DB_PASSWORD}@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/${DB_DATABASE}?serverVersion=5.7" >> .env
      - name: Prepare fresh Symfony app
        run: |
          cp -r symfony_app_tmp $SYMFONY_FOLDER 
      - name: Select branch to install module
        id: extract_branch
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "push" ]]; then
            echo "::set-output name=branch::$(echo ${GITHUB_REF##*/})"
          elif [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            echo "::set-output name=branch::$(echo $GITHUB_HEAD_REF)"
          else
            echo "::set-output name=branch::INVALID_EVENT_BRANCH_UNKNOWN"
          fi
      - name: Install module
        run: |
          cd $SYMFONY_FOLDER
          composer req "marvin255/doctrine-translation-bundle:dev-${{ steps.extract_branch.outputs.branch }}" -W
      - name: Check that module is auto enabled
        run: |
          cat $SYMFONY_FOLDER/config/bundles.php | grep "Marvin255DoctrineTranslationBundle"
      - name: Check that locale type is registered
        run: |
          $SYMFONY_FOLDER/bin/console debug:config doctrine dbal.types | grep "marvin255_locale"
      - name: Check that migrations for module are ok
        run: |
          cp ./.github/mock/Test.php $SYMFONY_FOLDER/src/Entity/Test.php
          cp ./.github/mock/TestTranslation.php $SYMFONY_FOLDER/src/Entity/TestTranslation.php
          $SYMFONY_FOLDER/bin/console make:migration
          $SYMFONY_FOLDER/bin/console doctrine:migrations:migrate
